apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: motoskia/nodetodoapp
        name: web
        env:
        - name: Url
          value: <<URL
        ports:
        - containerPort: 8080
          name: http-server
